kind = "web"
previewPath = "/"
title = "Fake Review Detector"
version = "1.0.0"
id = "artifacts/review-detector"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20446

[services.development]
run = "pnpm --filter @workspace/review-detector run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/review-detector", "run", "build" ]
publicDir = "artifacts/review-detector/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20446"
BASE_PATH = "/"

[[services]]
name = "ML API"
paths = ["/ml"]
localPort = 8090

[services.development]
run = "/home/runner/workspace/.pythonlibs/bin/python /home/runner/workspace/artifacts/review-api/main.py"

[services.env]
PORT = "8090"
